### ISSUE TITLE
Date and time pickers for countdown template

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#198] opened 2015-08-02 14:26 UTC
In the countdown template the user must enter a date and time for the countdown. However, it's not clear at all what format must be used in these fields, date and time pickers would be ideal but even a placeholder would be a great improvement

**Comment by atwellpub** [comment] 2015-08-03 18:16
Ok so:

* Add placeholders/description to help clarify? 

With inboundnow, any changes we make to files in our /shared/ folder must be made to our Calls to Action repository. 

Also any new commits must provide a short description on what the commit does and the commit must link directly to the issue it addresses. 

Here is where I think the changes should be made to render a placeholder:
https://github.com/inboundnow/cta/blob/master/shared/classes/class.form.php#L281-L301

And to define a placeholder:
https://github.com/inboundnow/landing-pages/blob/master/templates/countdown-lander/config.php#L64-L71

Please make sure that if no placeholder is present in a template's config file then no PHP soft errors are thrown.

**Comment by daprela** [comment] 2015-08-04 15:17
Something is wrong here. I don't think that class.form.php is the right place.
First of all, by looking at the html of the page I see that the two input fields are inside a div with class 'jquery-date-picker' which tells me that a date picker should show up when you select the fields.

Then, the ID of the date input field is 'date-picker-{url}' and from my search I see that it's defined only in the class.metaboxes.wp-call-to-action.php
This field is then used by the file picker_functions.js to show the date picker.

This needs to be investigated, I will make further research tomorrow but I think that here we should just enqueue the js script. I'll let you know

**Comment by atwellpub** [comment] 2015-08-04 17:32
Maybe it's this one? This method of if/else statement is where we render all inbound form fields. So it has to be one of these unless I'm gravely mistaken (it's a big plugin so I forget my way sometimes):

https://github.com/inboundnow/cta/blob/master/shared/classes/class.form.php#L250-L281

**Comment by daprela** [comment] 2015-08-05 09:19
Ok, I made it but there's something to say here before I push the change. The correct course of action is to make everything in the file config.php in a way similar to what I had made with the template tweet-to-download: register a js library and activate it so that it opens the date/time picker any time you click on one of the fields.

Problem #1: You have a js library called jquery-datepicker located in js/libraries which in reality is a library called timepicker.js. This library is not registered nor enqueued anywhere at the moment. The problem is that this library is made to generate only a time picker, and not a date picker.

Problem #2: If I try to enqueue this or any library located in js/libraries from the file config.php I get a 403 (forbidden) error. I don't understand why.

I have found a replacement for the jquery.datepicker library which can generate both a date and a time picker. Now, my proposal would be to completely replace the old limited library with this one in /js/libraries. The problem is the 403 error that I get. If I move the library under the templates/countdownlander directory it works.

So, you either have an explanation and a solution for that 403 error, or I keep the library as template specific.

What do you think?

**Comment by daprela** [comment] 2015-08-05 14:15
On a sidenote, I was thinking that it could be a good idea to register the library at the plugin admin_init hook, and then enqueue it whenever and wherever it's needed, provided that this is possible and doesn't raise another 403 error

**Comment by atwellpub** [comment] 2015-08-05 18:18
I checked into 'jquery-datepicker' and confirmed it is not being used. It was only in the CTA plugin and not in shared, whereas anything form related would have to be in shared.

It makes me think that it was enqueued for template settings only. We have no CTA templates that would use a datetime picker, and no reason to include them in the template settings render section here: https://github.com/inboundnow/cta/blob/08a31b4f47de6e88a1b99699acd972581a12cb41/classes/class.metaboxes.wp-call-to-action.php#L341-L517

In the commit below I removed the enqueue, the library, and the render_settings field support.

**Comment by atwellpub** [comment] 2015-08-05 18:27
"The correct course of action is to make everything in the file config.php in a way similar to what I had made with the template tweet-to-download: register a js library and activate it so that it opens the date/time picker any time you click on one of the fields." 

For landing pages  the correct way *would* be including the library and field support in config.php, but we wanted our date/time selectors as an available field for anyone wanting to use our field definitions tool. So we hardcoded support in here:
https://github.com/inboundnow/landing-pages/blob/master/classes/class.metaboxes.php#L907-L915

Please with this new information move forward as you see fit. I'll have to test similiar conditions to figure out why the 403 error does not work. 

I do not think we should setup the enqueue at config.php level, since other custom customer templates might depend on our current 'datepicker' field type being supported in core.

**Comment by daprela** [comment] 2015-08-06 03:39
On a sidenote, I was thinking that it could be a good idea to register the library at the plugin admin_init hook, and then enqueue it whenever and wherever it's needed, provided that this is possible and doesn't raise another 403 error

**Comment by daprela** [comment] 2015-08-06 03:41
We should move the datepicker case from class.metaboxes.php to the template at this point but for this my opinion is that we should open another issue

**Comment by atwellpub** [comment] 2015-08-06 19:49
We can't pull it out of class.metaboxes.php though because our premium countdown template depends on the presense of a 'datepicker' fieldtype in core. 

I'm going to move the enqueue out of  config and into class.metaboxes.php. I also moved all the relative enqueus found in class.post-type.php into class.metaboxes.php. 

Today I'm also going to be moving /js/ and /libraries/ files into the /assets folder.

**Comment by atwellpub** [comment] 2015-08-06 23:48
By the way good work the picker works good.

**Comment by daprela** [comment] 2015-08-07 00:34
Thank you Hudson, so, basically with this last edit you've made the new datepicker library available to all the landing page templates, is that right? I'm trying to learn how the plugin works

**Comment by atwellpub** [comment] 2015-08-07 01:29
Yes sir, though only two known inboundnow templates are leveraging the 'datepicker' field type atm.

**Closed** 2015-09-22 22:34 UTC
